#!/bin/bash


LOCALAUTOSTART=~/.i3autostart.local
    
xset dpms 300 600 900 

# start some programs here
owncloud &

# enable KDE bloat
# i have no idea why i need --check, but it only works this way:
kded4 --check
kded4
qdbus org.kde.kded /kded loadSecondPhase
qdbus org.kde.kded /kded loadModule powerdevil
qdbus org.kde.kded /kded loadModule networkmanagement

# restart akonadi
nepomukserver &
akonadictl start 


# now start some frontends
#kmix &
#smb4k &


# kill knotify4 if it is running
killall -9 knotify4

echo got here
#
# now start local programs if local file exists

if [ -x "$LOCALAUTOSTART" ]; then
    echo "starting stuff from local autostart script"
    $LOCALAUTOSTART 
else
    echo "no local autostart found ($LOCALAUTOSTART)"
fi
